/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 C:\Users\cgilb\Documents\Code\r3f\public\models\lamb02\scene.gltf --transform -jM 
Files: C:\Users\cgilb\Documents\Code\r3f\public\models\lamb02\scene.gltf [186.6KB] > scene-transformed.glb [635.38KB] (-241%)
Author: BRO (https://sketchfab.com/musawork786)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-lamborghini-revuelto-1a00d7d7fea6492bb960ec595cf79464
Title: Black Lamborghini_revuelto
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Front_part_6_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Daylight_Part_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Daylight_Part_Inside_Headlight_0.geometry} material={materials.Inside_Headlight} scale={0.01} />
      <mesh geometry={nodes.Daylight_Glass_Headlight_glass001_0.geometry} material={materials['Headlight_glass.001']} scale={0.01} />
      <mesh geometry={nodes.Daylight_Light_0.geometry} material={materials.Light} scale={0.01} />
      <mesh geometry={nodes.Tail_light_Taillight_glass_0.geometry} material={materials.Taillight_glass} scale={0.01} />
      <mesh geometry={nodes.Tail_light_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Tail_light_Tail_light_0.geometry} material={materials.Tail_light} scale={0.01} />
      <mesh geometry={nodes.Rear_plastic_part_1_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Exhaust_1_Exhaust_0.geometry} material={materials.Exhaust} scale={0.01} />
      <mesh geometry={nodes.Exhaust_1_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Rear_part_4_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Rear_part_3_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Rear_part_6_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Rear_vent_Vents_0.geometry} material={materials.Vents} scale={0.01} />
      <mesh geometry={nodes.Rear_part_2_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Rear_engine_carbon_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Rear_engine_carbon_Vents_0.geometry} material={materials.Vents} scale={0.01} />
      <mesh geometry={nodes.Rear_plastic_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Vents_rear_Vents_0.geometry} material={materials.Vents} scale={0.01} />
      <mesh geometry={nodes.Engine_Engine_0.geometry} material={materials.Engine} scale={[0.01, 0.01, 0.009]} />
      <mesh geometry={nodes.Front_part_9_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Front_part_9_Sphere_0.geometry} material={materials.Sphere} scale={0.01} />
      <mesh geometry={nodes.Front_vents_Plastic_0.geometry} material={materials.Plastic} scale={[0.01, 0.01, 0.009]} />
      <mesh geometry={nodes.Front_part_7_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Front_part_8001_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Front_part_8001_Sphere_0.geometry} material={materials.Sphere} scale={0.01} />
      <mesh geometry={nodes.Front_part_4_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Front_part_1_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Front_part_1_Metal_0.geometry} material={materials.Metal} scale={0.01} />
      <mesh geometry={nodes.Front_part_2_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Front_vents_2_Vents_0.geometry} material={materials.Vents} scale={0.01} />
      <mesh geometry={nodes.Rear_part_5_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Front_part_8_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Front_part_5_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Headlight_carbon_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Headlight_Headlight_0.geometry} material={materials.Headlight} scale={0.01} />
      <mesh geometry={nodes.Headlight_Headlight_ligh_second_0.geometry} material={materials.Headlight_ligh_second} scale={0.01} />
      <mesh geometry={nodes.Headlight_Headlight_light_0.geometry} material={materials.Headlight_light} scale={0.01} />
      <mesh geometry={nodes.Headlight_glass_Headlight_glass_0.geometry} material={materials.Headlight_glass} scale={0.01} />
      <mesh geometry={nodes.Exhaust_2_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Vents_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Vents_Vents_0.geometry} material={materials.Vents} scale={0.01} />
      <mesh geometry={nodes.Mid_part_3001_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Windshield_Windows_0.geometry} material={materials.Windows} scale={0.01} />
      <mesh geometry={nodes.Mid_part_3_Interior_black_0.geometry} material={materials.Interior_black} scale={0.01} />
      <mesh geometry={nodes['Right&Left_window_2_Windows_0'].geometry} material={materials.Windows} scale={0.01} />
      <mesh geometry={nodes.Brake_light_Tail_light_brake_0.geometry} material={materials.Tail_light_brake} scale={0.01} />
      <mesh geometry={nodes.Brake_light_Taillight_glass_0.geometry} material={materials.Taillight_glass} scale={0.01} />
      <mesh geometry={nodes['Right&Left_windows_Windows_0'].geometry} material={materials.Windows} scale={0.01} />
      <mesh geometry={nodes.Wheel_FR_Tire_0.geometry} material={materials.Tire} position={[1.226, 0.316, 0.82]} scale={0.003} />
      <mesh geometry={nodes.Wheel_BR_Tire_0.geometry} material={materials.Tire} position={[-1.342, 0.347, 0.805]} scale={0.003} />
      <mesh geometry={nodes.Wheel_FR_Logo_0.geometry} material={materials.Logo} position={[1.226, 0.316, 0.82]} scale={0.003} />
      <mesh geometry={nodes.Wheel_BR_Logo_0.geometry} material={materials.Logo} position={[-1.342, 0.347, 0.805]} scale={0.003} />
      <mesh geometry={nodes.Wheel_FR_Caliper_0.geometry} material={materials.Caliper} position={[1.226, 0.316, 0.82]} scale={0.003} />
      <mesh geometry={nodes.Wheel_BR_Caliper_0.geometry} material={materials.Caliper} position={[-1.342, 0.347, 0.805]} scale={0.003} />
      <mesh geometry={nodes.Wheel_FR_Brake_rotor_0.geometry} material={materials.Brake_rotor} position={[1.226, 0.316, 0.82]} scale={0.003} />
      <mesh geometry={nodes.Wheel_BR_Brake_rotor_0.geometry} material={materials.Brake_rotor} position={[-1.342, 0.347, 0.805]} scale={0.003} />
      <mesh geometry={nodes.Wheel_FR_Rim_0.geometry} material={materials.material} position={[1.226, 0.316, 0.82]} scale={0.003} />
      <mesh geometry={nodes.Wheel_BR_Rim_0.geometry} material={materials.material} position={[-1.342, 0.347, 0.805]} scale={0.003} />
      <mesh geometry={nodes.Hood075_Turning_light_right_0.geometry} material={materials.Turning_light_right} scale={0.01} />
      <mesh geometry={nodes.Hood075_Turning_light_Left_0.geometry} material={materials.Turning_light_right} scale={0.01} />
      <mesh geometry={nodes.Hood075_Body_0.geometry} material={materials.Body} scale={0.01} />
      <mesh geometry={nodes.Hood075_Turning_light_inside_0.geometry} material={materials.Turning_light_inside} scale={0.01} />
      <mesh geometry={nodes.Hood075_Interior_black_0.geometry} material={materials.Interior_black} scale={0.01} />
      <mesh geometry={nodes.Hood075_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Hood075_Turning_light_glass_0.geometry} material={materials.Turning_light_glass} scale={0.01} />
      <mesh geometry={nodes.Interior_doors_Interior_black_0.geometry} material={materials.Interior_black} scale={0.01} />
      <mesh geometry={nodes.Interior_doors_Interior_color_0.geometry} material={materials.Interior_color} scale={0.01} />
      <mesh geometry={nodes.Interior_general_Interior_black_0.geometry} material={materials.Interior_black} scale={0.01} />
      <mesh geometry={nodes.Interior_middle_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Interior_middle_Steering_wheel_0.geometry} material={materials.Steering_wheel} scale={0.01} />
      <mesh geometry={nodes.Rear_window_Windows_0.geometry} material={materials.Windows} scale={0.01} />
      <mesh geometry={nodes.Interior_middle_parts_Interior_color_0.geometry} material={materials.Interior_color} scale={0.01} />
      <mesh geometry={nodes.Interior_middle_parts_Interior_black_0.geometry} material={materials.Interior_black} scale={0.01} />
      <mesh geometry={nodes.Interior_middle_parts_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Interior_middle_parts_Start_button_lol_0.geometry} material={materials.Start_button_lol} scale={0.01} />
      <mesh geometry={nodes.Seat_Interior_color_0.geometry} material={materials.Interior_color} rotation={[0, Math.PI / 2, 0]} scale={0.006} />
      <mesh geometry={nodes.Seat_Interior_Black_0.geometry} material={materials.Interior_Black} rotation={[0, Math.PI / 2, 0]} scale={0.006} />
      <mesh geometry={nodes.Mid_part_2_Interior_Black_0.geometry} material={materials.Interior_Black} scale={0.01} />
      <mesh geometry={nodes.Mid_parts_1_Plastic_0.geometry} material={materials.Plastic} scale={0.01} />
      <mesh geometry={nodes.Pedal_Metal_0.geometry} material={materials.Metal} scale={0.01} />
      <mesh geometry={nodes.Steering_wheel_Logo_0.geometry} material={materials.Logo} position={[0.459, 0.662, -0.394]} scale={0.01} />
      <mesh geometry={nodes.Steering_wheel_Steering_wheel_0.geometry} material={materials.Steering_wheel} position={[0.459, 0.662, -0.394]} scale={0.01} />
      <mesh geometry={nodes.Steering_wheel_holder_Interior_black_0.geometry} material={materials.Interior_black} scale={0.01} />
      <mesh geometry={nodes.Speedometer_Cluster_0.geometry} material={materials.Cluster} scale={0.01} />
      <mesh geometry={nodes.Speedometer_Interior_black_0.geometry} material={materials.Interior_black} scale={0.01} />
      <mesh geometry={nodes.Mirrors_Body_0.geometry} material={materials.Body} scale={0.01} />
      <mesh geometry={nodes.Mirrors_mirror_0.geometry} material={materials.mirror} scale={0.01} />
      <mesh geometry={nodes.Mirrors_Carbon_0.geometry} material={materials.Carbon} scale={0.01} />
      <mesh geometry={nodes.Wheel_FL_Tire_0.geometry} material={materials.Tire} position={[1.226, 0.316, -0.82]} scale={0.01} />
      <mesh geometry={nodes.Wheel_FL_Logo_0.geometry} material={materials.Logo} position={[1.226, 0.316, -0.82]} scale={0.01} />
      <mesh geometry={nodes.Wheel_FL_Caliper_0.geometry} material={materials.Caliper} position={[1.226, 0.316, -0.82]} scale={0.01} />
      <mesh geometry={nodes.Wheel_FL_Brake_rotor_0.geometry} material={materials.Brake_rotor} position={[1.226, 0.316, -0.82]} scale={0.01} />
      <mesh geometry={nodes.Wheel_FL_Rim_0.geometry} material={materials.material} position={[1.226, 0.316, -0.82]} scale={0.01} />
      <mesh geometry={nodes.Wheel_BL_Tire_0.geometry} material={materials.Tire} position={[-1.342, 0.347, -0.805]} scale={0.01} />
      <mesh geometry={nodes.Wheel_BL_Logo_0.geometry} material={materials.Logo} position={[-1.342, 0.347, -0.805]} scale={0.01} />
      <mesh geometry={nodes.Wheel_BL_Caliper_0.geometry} material={materials.Caliper} position={[-1.342, 0.347, -0.805]} scale={0.01} />
      <mesh geometry={nodes.Wheel_BL_Brake_rotor_0.geometry} material={materials.Brake_rotor} position={[-1.342, 0.347, -0.805]} scale={0.01} />
      <mesh geometry={nodes.Wheel_BL_Rim_0.geometry} material={materials.material} position={[-1.342, 0.347, -0.805]} scale={0.01} />
      <mesh geometry={nodes.Rear_engine_carbon_vents_Vents_0.geometry} material={materials.Vents} scale={0.01} />
      <mesh geometry={nodes.Rear_part_3001_Taillight_rear_0.geometry} material={materials.Taillight_rear} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
